WITH ohlc_volatility AS (
    SELECT 
        CRYPTO_ID,
        OHLC_TIMESTAMP::DATE AS TRADE_DATE,
        CLOSE_PRICE,
        HIGH_PRICE,
        LOW_PRICE,
        (HIGH_PRICE - LOW_PRICE) / NULLIF(CLOSE_PRICE, 0) * 100 AS DAILY_VOLATILITY_PERCENTAGE
    FROM TER_DATABASE.TER_RAW_DATA.COINGECKO_OHLC_DATA
),
volatility_analysis AS (
    SELECT 
        p.CRYPTO_ID,
        c.SYMBOL,
        c.NAME,
        p.TRADE_DATE,
        p.DAILY_VOLATILITY_PERCENTAGE,
        c.MARKET_CAP,
        c.CIRCULATING_SUPPLY,
        c.TOTAL_SUPPLY,
        c.ATH,
        c.ATL
    FROM ohlc_volatility p
    JOIN {{ ref('transformed_coingecko_data_v') }} c
        ON p.CRYPTO_ID = c.ID
)
SELECT 
    CRYPTO_ID,
    SYMBOL,
    NAME,
    AVG(DAILY_VOLATILITY_PERCENTAGE) AS AVG_DAILY_VOLATILITY,
    AVG(NULLIF(MARKET_CAP, 0)) AS AVG_MARKET_CAP,
    (CIRCULATING_SUPPLY / NULLIF(TOTAL_SUPPLY, 0)) * 100 AS SUPPLY_RATIO_PERCENTAGE,
    (CLOSE_PRICE - ATH) / NULLIF(ATH, 0) * 100 AS DISTANCE_TO_ATH_PERCENTAGE,
    (CLOSE_PRICE - ATL) / NULLIF(ATL, 0) * 100 AS DISTANCE_TO_ATL_PERCENTAGE
FROM volatility_analysis
GROUP BY CRYPTO_ID, SYMBOL, NAME, CIRCULATING_SUPPLY, TOTAL_SUPPLY, ATH, ATL, CLOSE_PRICE
ORDER BY AVG_DAILY_VOLATILITY DESC
LIMIT 20